#!/usr/bin/env bash
#
# Download all paired OAS sequences

export OAS_DOWNLOAD_DIR="${HOME}/Downloads/oas_paired"
mkdir -p "$OAS_DOWNLOAD_DIR"

echo "Downloading OAS database to $OAS_DOWNLOAD_DIR"

download_url() {
  curl -sSL -o "$1/$(basename "$2")" "$2"
}

export -f download_url

if type parallel >/dev/null 2>&1; then
    echo 'using parallel'
    parallel --eta download_url "$OAS_DOWNLOAD_DIR" :::: oas_paired_urls.txt
else
    echo 'using xargs'
    xargs -P "$(nproc)" -a oas_paired_urls.txt -I{} bash -c 'curl -sSL -o "$0/$(basename "$1")" "$1"' "$OAS_DOWNLOAD_DIR" {}
fi
